# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/charles/Documents/misc_alg/cpp_train/boids

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/charles/Documents/misc_alg/cpp_train/boids

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/charles/Documents/misc_alg/cpp_train/boids/CMakeFiles /home/charles/Documents/misc_alg/cpp_train/boids/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/charles/Documents/misc_alg/cpp_train/boids/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenGLExample

# Build rule for target.
OpenGLExample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenGLExample
.PHONY : OpenGLExample

# fast build rule for target.
OpenGLExample/fast:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/build
.PHONY : OpenGLExample/fast

src/common/controls.o: src/common/controls.cpp.o

.PHONY : src/common/controls.o

# target to build an object file
src/common/controls.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/controls.cpp.o
.PHONY : src/common/controls.cpp.o

src/common/controls.i: src/common/controls.cpp.i

.PHONY : src/common/controls.i

# target to preprocess a source file
src/common/controls.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/controls.cpp.i
.PHONY : src/common/controls.cpp.i

src/common/controls.s: src/common/controls.cpp.s

.PHONY : src/common/controls.s

# target to generate assembly for a file
src/common/controls.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/controls.cpp.s
.PHONY : src/common/controls.cpp.s

src/common/objloader.o: src/common/objloader.cpp.o

.PHONY : src/common/objloader.o

# target to build an object file
src/common/objloader.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/objloader.cpp.o
.PHONY : src/common/objloader.cpp.o

src/common/objloader.i: src/common/objloader.cpp.i

.PHONY : src/common/objloader.i

# target to preprocess a source file
src/common/objloader.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/objloader.cpp.i
.PHONY : src/common/objloader.cpp.i

src/common/objloader.s: src/common/objloader.cpp.s

.PHONY : src/common/objloader.s

# target to generate assembly for a file
src/common/objloader.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/objloader.cpp.s
.PHONY : src/common/objloader.cpp.s

src/common/quaternion_utils.o: src/common/quaternion_utils.cpp.o

.PHONY : src/common/quaternion_utils.o

# target to build an object file
src/common/quaternion_utils.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/quaternion_utils.cpp.o
.PHONY : src/common/quaternion_utils.cpp.o

src/common/quaternion_utils.i: src/common/quaternion_utils.cpp.i

.PHONY : src/common/quaternion_utils.i

# target to preprocess a source file
src/common/quaternion_utils.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/quaternion_utils.cpp.i
.PHONY : src/common/quaternion_utils.cpp.i

src/common/quaternion_utils.s: src/common/quaternion_utils.cpp.s

.PHONY : src/common/quaternion_utils.s

# target to generate assembly for a file
src/common/quaternion_utils.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/quaternion_utils.cpp.s
.PHONY : src/common/quaternion_utils.cpp.s

src/common/shader.o: src/common/shader.cpp.o

.PHONY : src/common/shader.o

# target to build an object file
src/common/shader.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/shader.cpp.o
.PHONY : src/common/shader.cpp.o

src/common/shader.i: src/common/shader.cpp.i

.PHONY : src/common/shader.i

# target to preprocess a source file
src/common/shader.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/shader.cpp.i
.PHONY : src/common/shader.cpp.i

src/common/shader.s: src/common/shader.cpp.s

.PHONY : src/common/shader.s

# target to generate assembly for a file
src/common/shader.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/shader.cpp.s
.PHONY : src/common/shader.cpp.s

src/common/tangentspace.o: src/common/tangentspace.cpp.o

.PHONY : src/common/tangentspace.o

# target to build an object file
src/common/tangentspace.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/tangentspace.cpp.o
.PHONY : src/common/tangentspace.cpp.o

src/common/tangentspace.i: src/common/tangentspace.cpp.i

.PHONY : src/common/tangentspace.i

# target to preprocess a source file
src/common/tangentspace.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/tangentspace.cpp.i
.PHONY : src/common/tangentspace.cpp.i

src/common/tangentspace.s: src/common/tangentspace.cpp.s

.PHONY : src/common/tangentspace.s

# target to generate assembly for a file
src/common/tangentspace.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/tangentspace.cpp.s
.PHONY : src/common/tangentspace.cpp.s

src/common/text2D.o: src/common/text2D.cpp.o

.PHONY : src/common/text2D.o

# target to build an object file
src/common/text2D.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/text2D.cpp.o
.PHONY : src/common/text2D.cpp.o

src/common/text2D.i: src/common/text2D.cpp.i

.PHONY : src/common/text2D.i

# target to preprocess a source file
src/common/text2D.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/text2D.cpp.i
.PHONY : src/common/text2D.cpp.i

src/common/text2D.s: src/common/text2D.cpp.s

.PHONY : src/common/text2D.s

# target to generate assembly for a file
src/common/text2D.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/text2D.cpp.s
.PHONY : src/common/text2D.cpp.s

src/common/texture.o: src/common/texture.cpp.o

.PHONY : src/common/texture.o

# target to build an object file
src/common/texture.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/texture.cpp.o
.PHONY : src/common/texture.cpp.o

src/common/texture.i: src/common/texture.cpp.i

.PHONY : src/common/texture.i

# target to preprocess a source file
src/common/texture.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/texture.cpp.i
.PHONY : src/common/texture.cpp.i

src/common/texture.s: src/common/texture.cpp.s

.PHONY : src/common/texture.s

# target to generate assembly for a file
src/common/texture.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/texture.cpp.s
.PHONY : src/common/texture.cpp.s

src/common/vboindexer.o: src/common/vboindexer.cpp.o

.PHONY : src/common/vboindexer.o

# target to build an object file
src/common/vboindexer.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/vboindexer.cpp.o
.PHONY : src/common/vboindexer.cpp.o

src/common/vboindexer.i: src/common/vboindexer.cpp.i

.PHONY : src/common/vboindexer.i

# target to preprocess a source file
src/common/vboindexer.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/vboindexer.cpp.i
.PHONY : src/common/vboindexer.cpp.i

src/common/vboindexer.s: src/common/vboindexer.cpp.s

.PHONY : src/common/vboindexer.s

# target to generate assembly for a file
src/common/vboindexer.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/common/vboindexer.cpp.s
.PHONY : src/common/vboindexer.cpp.s

src/window.o: src/window.cpp.o

.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i

.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s

.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLExample.dir/build.make CMakeFiles/OpenGLExample.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... OpenGLExample"
	@echo "... src/common/controls.o"
	@echo "... src/common/controls.i"
	@echo "... src/common/controls.s"
	@echo "... src/common/objloader.o"
	@echo "... src/common/objloader.i"
	@echo "... src/common/objloader.s"
	@echo "... src/common/quaternion_utils.o"
	@echo "... src/common/quaternion_utils.i"
	@echo "... src/common/quaternion_utils.s"
	@echo "... src/common/shader.o"
	@echo "... src/common/shader.i"
	@echo "... src/common/shader.s"
	@echo "... src/common/tangentspace.o"
	@echo "... src/common/tangentspace.i"
	@echo "... src/common/tangentspace.s"
	@echo "... src/common/text2D.o"
	@echo "... src/common/text2D.i"
	@echo "... src/common/text2D.s"
	@echo "... src/common/texture.o"
	@echo "... src/common/texture.i"
	@echo "... src/common/texture.s"
	@echo "... src/common/vboindexer.o"
	@echo "... src/common/vboindexer.i"
	@echo "... src/common/vboindexer.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

